/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsWorkspaceRouteImport } from './routes/settings.workspace'
import { Route as OrgIdRouteImport } from './routes/org/$id'
import { Route as DevDiffRouteImport } from './routes/_dev.diff'
import { Route as OrgIdIndexRouteImport } from './routes/org/$id.index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWorkspaceRoute = SettingsWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => SettingsRoute,
} as any)
const OrgIdRoute = OrgIdRouteImport.update({
  id: '/org/$id',
  path: '/org/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDiffRoute = DevDiffRouteImport.update({
  id: '/_dev/diff',
  path: '/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIdIndexRoute = OrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/diff': typeof DevDiffRoute
  '/org/$id': typeof OrgIdRouteWithChildren
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/org/$id/': typeof OrgIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/diff': typeof DevDiffRoute
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/org/$id': typeof OrgIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/_dev/diff': typeof DevDiffRoute
  '/org/$id': typeof OrgIdRouteWithChildren
  '/settings/workspace': typeof SettingsWorkspaceRoute
  '/org/$id/': typeof OrgIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/settings'
    | '/diff'
    | '/org/$id'
    | '/settings/workspace'
    | '/org/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/settings'
    | '/diff'
    | '/settings/workspace'
    | '/org/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/settings'
    | '/_dev/diff'
    | '/org/$id'
    | '/settings/workspace'
    | '/org/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  DevDiffRoute: typeof DevDiffRoute
  OrgIdRoute: typeof OrgIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/workspace': {
      id: '/settings/workspace'
      path: '/workspace'
      fullPath: '/settings/workspace'
      preLoaderRoute: typeof SettingsWorkspaceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/org/$id': {
      id: '/org/$id'
      path: '/org/$id'
      fullPath: '/org/$id'
      preLoaderRoute: typeof OrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dev/diff': {
      id: '/_dev/diff'
      path: '/diff'
      fullPath: '/diff'
      preLoaderRoute: typeof DevDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$id/': {
      id: '/org/$id/'
      path: '/'
      fullPath: '/org/$id/'
      preLoaderRoute: typeof OrgIdIndexRouteImport
      parentRoute: typeof OrgIdRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsWorkspaceRoute: typeof SettingsWorkspaceRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsWorkspaceRoute: SettingsWorkspaceRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface OrgIdRouteChildren {
  OrgIdIndexRoute: typeof OrgIdIndexRoute
}

const OrgIdRouteChildren: OrgIdRouteChildren = {
  OrgIdIndexRoute: OrgIdIndexRoute,
}

const OrgIdRouteWithChildren = OrgIdRoute._addFileChildren(OrgIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  DevDiffRoute: DevDiffRoute,
  OrgIdRoute: OrgIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
